device: 'cpu'

test_name: 'test_models_trained_synthetic_data'

test_dataset:
  path: '../dataset_test_multiplenoise_from_SGT_4000_to_5000.h5'
  type: 'DatasetSpgramSyntheticData'


hop_values:
        - 10
        - 14
        - 18
        - 22
        - 26
        - 30
        - 34

model_names: 
        - '../model_hop_10_3500GT/models/model_hop_10_3500GT_best.pt'
        - '../model_hop_14_3500GT/models/model_hop_14_3500GT_best.pt'
        - '../model_hop_18_3500GT/models/model_hop_18_3500GT_best.pt'
        - '../model_hop_22_3500GT/models/model_hop_22_3500GT_best.pt'
        - '../model_hop_26_3500GT/models/model_hop_26_3500GT_best.pt'
        - '../model_hop_30_3500GT/models/model_hop_30_3500GT_best.pt'
        - '../model_hop_34_3500GT/models/model_hop_34_3500GT_best.pt'

model_nicknames:
        - 'vit_10'
        - 'vit_14'
        - 'vit_18'
        - 'vit_22'
        - 'vit_26'
        - 'vit_30'
        - 'vit_34'


show_results_for_each_hop: True
show_results_for_all_hops_combined: True
