model:
  name_model: "model_hop_10_realdata_SpVit_separatefiles_nonoise"
  dir_save_results: "../model_hop_10_realdata_SpVit_separatefiles_nonoise/"
  new_model: True
  path_to_saved_model: ""

data:
  data_folder: "../dataset_spectrovit_only_phillips/"
  augment_with_noise_train: False
  augment_with_noise_validation: False
  hop_size: 10
  random_augment:
      amplitude:
        noise_level_base:
          max: 2
          min: 0
        noise_level_scan_var:
          max: 2
          min: 0
      frequency:
        noise_level_base:
          max: 2
          min: 0
        noise_level_scan_var:
          max: 2
          min: 0
      phase:
        noise_level_base:
          max: 2
          min: 0
        noise_level_scan_var:
          max: 2
          min: 0

dataset: "DatasetRealDataSeparateFiles"

training:
  batch_size_train: 100
  batch_size_validation: 6
  n_epochs: 30

loss: "RangeMAELossPPMVary"

optimizer:
  Adam:
    lr: 0.0001
  path_to_saved_optimizer: ""

lr_scheduler:
  activate: True
  path_to_saved_scheduler: ""
  scheduler_type: "cosineannealinglr"
  epoch_to_switch_to_lr_scheduler: 20
  initial_lr_scheduler: 0.00001
  info:
    T_max: 10
    eta_min: 0.000001
  

save_models_and_results:
  step_to_safe_save_models: 5
  step_for_saving_plots: 3
  save_best_model: True

wandb:
  activate: False


